# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 14:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 22, 14, 22, 53, 621432, tzinfo=utc)),
        ),
    ]
